### ISSUE TITLE
Auto-Positioning of messages with many lines

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#308]
https://discord.com/channels/942484331572658196/942484835631521812/1035927363608903752

**Comment by MunWolf** [comment]
Transcript

There seems to be a regression on the positioning of message boxes with many lines
1.10.2, 10 lines (maximum in that version)
Image
2.2.1, 10 lines
Image
2.2.1, 20 lines (should be about the maximum that could fit on the screen)
Image
Presumably with many lines the top padding of the messagebox gets stretched, and that determines the distance from the top as well
The stretching itself looks weird too, would consider that in itself a visual "bug" in addition to the functionality "bug", although of course both just stem from the base game not having built the system for that many lines
This is relevant for the quest helper currently, which has to display in two pages because even though one page should fit on the screen, the positioning prevents that from working
I was also building on a "All collected Bonus Upgrades" display, which also struggles to work around this issue
Would probably prefer to freeze that feature until the positioning gets improved
